' Configure layout
!global $FONT_COLOR?="#3b3b3b"
!global $LIGHT_FONT_COLOR?="Grey"
!global $FONT_SIZE_XS?=10
!global $FONT_SIZE_SM?=12
!global $FONT_SIZE_MD?=16
!global $FONT_SIZE_LG?=20


' Common Procedures
!procedure Title($title, $subtitle="", $version="", $date="")
  title
  <color:$FONT_COLOR><size:$FONT_SIZE_LG>$title</size></color>
  !if ($subtitle)
    <color:$LIGHT_FONT_COLOR><size:$FONT_SIZE_MD><i>$subtitle</i></size></color>
  !endif
  !if ($version)
    <color:$LIGHT_FONT_COLOR><size:$FONT_SIZE_SM>Version: $version</size></color>
  !endif
  !if ($date)
    <color:$LIGHT_FONT_COLOR><size:$FONT_SIZE_SM>Last modified: $date</size></color>
  !endif
  end title
!endprocedure

!procedure SketchMode()
  !$counter=0
  !foreach $versionPart in %splitstr(%version(), ".")
    !$counter=$counter+1

    !if ($counter == 2)
      !$year=$versionPart
    !endif

    !if ($counter == 3)
      !$minor=$versionPart
    !endif
  !endfor

  !if ($year < 2025) || ($year == 2025 && $minor == 0)
    skinparam handwritten true
  !else
    !option handwritten true
  !endif

  center footer
    <size:$FONT_SIZE_SM><color:red>WARNING</color> <color:$LIGHT_FONT_COLOR>this sketch required validation.<br>Do not use for production.</color></size>
  end footer
!endprocedure

!unquoted procedure Card($id, $shape, $stereotype, $name="")
  !if ($name == "")
    $name = "$id"
  !endif
  $shape $id <<$stereotype>> as "$name"
!endprocedure
