!$LIB_BASE?="https://raw.githubusercontent.com/sidneydemoraes/libs-plantuml/main"
!include $LIB_BASE/common.puml

!global $EVENT_BG_COLOR?="Orange"
!global $COMMAND_BG_COLOR?="MediumTurquoise"

left to right direction 

!unquoted procedure ESCard($id, $stereotype, $name="", &originId="")
  Card($id, rectangle, $stereotype, $name)
  !if ($originCommandId != "")
    $originId --> $id
  !endif
!endprocedure

!procedure Event($id, $name="", $originId="")
  ESCard($id, DomainEvent, $name, $originId)
!endprocedure

skinparam rectangle<<DomainEvent>> {
  BackgroundColor $EVENT_BG_COLOR
  FontColor $FONT_COLOR
}

!procedure Command($id, $name="", $originId="" )
  ESCard($id, Command, $name, $originId)
!endprocedure 

skinparam rectangle<<Command>> {
  BackgroundColor $COMMAND_BG_COLOR
  FontColor $FONT_COLOR
}