!$LIB_BASE?="https://raw.githubusercontent.com/sidcoelho/libs-plantuml/main"
!include $LIB_BASE/common.puml

!global $EVENT_BG_COLOR?="Orange"
!global $COMMAND_BG_COLOR?="MediumTurquoise"
!global $SYSTEM_BG_COLOR?="Pink"
!global $AGGREGATE_BG_COLOR?="LightGoldenRodYellow"
!global $ACTOR_BG_COLOR?="Gold"
!global $POLICY_BG_COLOR?="MediumPurple"
!global $READ_MODEL_BG_COLOR?="YellowGreen"

left to right direction

skinparam rectangle {
  FontColor $FONT_COLOR
}

!unquoted procedure ESCard($id, $stereotype, $name="", $originId="", $connDirection="")
  Card($id, rectangle, $stereotype, $name)
  !if ($originId != "")
    !$dir = %lower($connDirection)

    !if ($dir == "up" || $dir == "u")
      $originId -up-> $id
    !elseif ($dir == "down" || $dir == "d")
      $originId -down-> $id
    !elseif ($dir == "left" || $dir == "l")
      $originId -left-> $id
    !elseif ($dir == "right" || $dir == "r")
      $originId -right-> $id
    !else
      $originId --> $id
    !endif
  !endif
!endprocedure

!procedure Event($id, $name="", $originId="", $connDirection="")
  ESCard($id, DomainEvent, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<DomainEvent>> {
  BackgroundColor $EVENT_BG_COLOR
}

!procedure Command($id, $name="", $originId="", $connDirection="")
  ESCard($id, Command, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<Command>> {
  BackgroundColor $COMMAND_BG_COLOR
}

!procedure System($id, $name="", $originId="", $connDirection="")
  ESCard($id, System, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<System>> {
  BackgroundColor $SYSTEM_BG_COLOR
}

!procedure Aggregate($id, $name="", $originId="", $connDirection="")
  ESCard($id, Aggregate, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<Aggregate>> {
  BackgroundColor $AGGREGATE_BG_COLOR
}

!procedure Actor($id, $name="", $originId="", $connDirection="")
  ESCard($id, Actor, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<Actor>> {
  BackgroundColor $ACTOR_BG_COLOR
}

!procedure Policy($id, $name="", $originId="", $connDirection="")
  ESCard($id, Policy, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<Policy>> {
  BackgroundColor $POLICY_BG_COLOR
}

!procedure ReadModel($id, $name="", $originId="", $connDirection="")
  ESCard($id, ReadModel, $name, $originId, $connDirection)
!endprocedure

skinparam rectangle<<ReadModel>> {
  BackgroundColor $READ_MODEL_BG_COLOR
}
