!$LIB_BASE?="https://raw.githubusercontent.com/sidcoelho/libs-plantuml/main"
!include $LIB_BASE/common.puml

!global $EVENT_BG_COLOR?="Orange"
!global $COMMAND_BG_COLOR?="MediumTurquoise"
!global $SYSTEM_BG_COLOR?="Pink"
!global $AGGREGATE_BG_COLOR?="LightGoldenRodYellow"
!global $ACTOR_BG_COLOR?="Gold"
!global $POLICY_BG_COLOR?="MediumPurple"
!global $READ_MODEL_BG_COLOR?="YellowGreen"

left to right direction

skinparam rectangle {
  FontColor $FONT_COLOR
}

!unquoted procedure ESCard($id, $stereotype, $name="", $originId="")
  Card($id, rectangle, $stereotype, $name)
  !if ($originCommandId != "")
    $originId --> $id
  !endif
!endprocedure

!procedure Event($id, $name="", $originId="")
  ESCard($id, DomainEvent, $name, $originId)
!endprocedure

skinparam rectangle<<DomainEvent>> {
  BackgroundColor $EVENT_BG_COLOR
}

!procedure Command($id, $name="", $originId="" )
  ESCard($id, Command, $name, $originId)
!endprocedure

skinparam rectangle<<Command>> {
  BackgroundColor $COMMAND_BG_COLOR
}

!procedure System($id, $name="", $originId="" )
  ESCard($id, System, $name, $originId)
!endprocedure

skinparam rectangle<<System>> {
  BackgroundColor $SYSTEM_BG_COLOR
}

!procedure Aggregate($id, $name="", $originId="" )
  ESCard($id, Aggregate, $name, $originId)
!endprocedure

skinparam rectangle<<Aggregate>> {
  BackgroundColor $AGGREGATE_BG_COLOR
}

!procedure Actor($id, $name="", $originId="" )
  ESCard($id, Actor, $name, $originId)
!endprocedure

skinparam rectangle<<Actor>> {
  BackgroundColor $ACTOR_BG_COLOR
}

!procedure Policy($id, $name="", $originId="" )
  ESCard($id, Policy, $name, $originId)
!endprocedure

skinparam rectangle<<Policy>> {
  BackgroundColor $POLICY_BG_COLOR
}

!procedure ReadModel($id, $name="", $originId="" )
  ESCard($id, ReadModel, $name, $originId)
!endprocedure

skinparam rectangle<<ReadModel>> {
  BackgroundColor $READ_MODEL_BG_COLOR
}
